// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Uc3m3HKQUpS37kA84nlwhX_bvxdzHA',
    appId: '1:434143721032:web:03378c01e7f47ffbb1ca7d',
    messagingSenderId: '434143721032',
    projectId: 'chat-app-13ae4',
    authDomain: 'chat-app-13ae4.firebaseapp.com',
    storageBucket: 'chat-app-13ae4.appspot.com',
    measurementId: 'G-L4431ET194',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0FpgQJJEqmQiwR-SEoMUtl-mVXui_J8',
    appId: '1:434143721032:android:09caebf04fc90af1b1ca7d',
    messagingSenderId: '434143721032',
    projectId: 'chat-app-13ae4',
    storageBucket: 'chat-app-13ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQl-TT3wlS0qevwtxmXhwZeAYyn2E4cmA',
    appId: '1:434143721032:ios:09ea2d114a738261b1ca7d',
    messagingSenderId: '434143721032',
    projectId: 'chat-app-13ae4',
    storageBucket: 'chat-app-13ae4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQl-TT3wlS0qevwtxmXhwZeAYyn2E4cmA',
    appId: '1:434143721032:ios:09ea2d114a738261b1ca7d',
    messagingSenderId: '434143721032',
    projectId: 'chat-app-13ae4',
    storageBucket: 'chat-app-13ae4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ_Uc3m3HKQUpS37kA84nlwhX_bvxdzHA',
    appId: '1:434143721032:web:920d6e74fe38a55ab1ca7d',
    messagingSenderId: '434143721032',
    projectId: 'chat-app-13ae4',
    authDomain: 'chat-app-13ae4.firebaseapp.com',
    storageBucket: 'chat-app-13ae4.appspot.com',
    measurementId: 'G-098ZZZ72LN',
  );
}
